export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT';

export const OPEN_INGREDIENT = 'OPEN_INGREDIENT';
export const CLOSE_INGREDIENT = 'CLOSE_INGREDIENT';

export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';

export const POST_ORDER = 'POST_ORDER';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED';
export const ADD_INGREDIENT_ID = 'ADD_INGREDIENT_ID';
export const REMOVE_ORDER_ID = 'REMOVE_ORDER_ID';

export const POST_AUTHORIZATION = 'POST_AUTHORIZATION';
export const POST_AUTHORIZATION_SUCCESS = 'POST_AUTHORIZATION_SUCCESS';
export const POST_AUTHORIZATION_FAILED = 'POST_AUTHORIZATION_FAILED';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const CHANGE_USER_UPDATE = 'CHANGE_USER_UPDATE';


export const WS_ORDER_FEED_CONNECT: 'WS_ORDER_FEED_CONNECT' = 'WS_ORDER_FEED_CONNECT';
export const WS_ORDER_FEED_DISCONNECT: 'WS_ORDER_FEED_DISCONNECT' = 'WS_ORDER_FEED_DISCONNECT';
export const WS_ORDER_FEED_CONNECTING: 'WS_ORDER_FEED_CONNECTING' = 'WS_ORDER_FEED_CONNECTING';
export const WS_ORDER_FEED_OPEN: 'WS_ORDER_FEED_OPEN' = 'WS_ORDER_FEED_OPEN';
export const WS_ORDER_FEED_CLOSE: 'WS_ORDER_FEED_CLOSE' = 'WS_ORDER_FEED_CLOSE';
export const WS_ORDER_FEED_MESSAGE: 'WS_ORDER_FEED_MESSAGE' = 'WS_ORDER_FEED_MESSAGE';
export const WS_ORDER_FEED_ERROR: 'WS_ORDER_FEED_ERROR' = 'WS_ORDER_FEED_ERROR';

export const WS_USER_FEED_CONNECT: 'WS_USER_FEED_CONNECT' = 'WS_USER_FEED_CONNECT';
export const WS_USER_FEED_DISCONNECT: 'WS_USER_FEED_DISCONNECT' = 'WS_USER_FEED_DISCONNECT';
export const WS_USER_FEED_CONNECTING: 'WS_USER_FEED_CONNECTING' = 'WS_USER_FEED_CONNECTING';
export const WS_USER_FEED_OPEN: 'WS_USER_FEED_OPEN' = 'WS_USER_FEED_OPEN';
export const WS_USER_FEED_CLOSE: 'WS_USER_FEED_CLOSE' = 'WS_USER_FEED_CLOSE';
export const WS_USER_FEED_MESSAGE: 'WS_USER_FEED_MESSAGE' = 'WS_USER_FEED_MESSAGE';
export const WS_USER_FEED_ERROR: 'WS_USER_FEED_ERROR' = 'WS_USER_FEED_ERROR';